import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ChatWidget from "@/components/ChatWidget";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Set tema sebelum React hydration */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(() => { try {
              const theme = localStorage.getItem('theme');
              const d = document.documentElement;
              if (theme === 'dark') {
                d.classList.add('dark');
              } else if (theme === 'light') {
                d.classList.remove('dark');
              } else if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {
                d.classList.add('dark');
              }
            } catch (e) {} })();`,
          }}
        />
        {children}
        <ChatWidget />
      </body>
    </html>
  );
}
